spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-teste
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      concurrency: 10
  data:
    mongodb:
      uri: mongodb://localhost:27017/teste-performance